### ISSUE TITLE
Unable to run MicroWineBar due to tkinter module not found

### ISSUE THREAD

**Issue by Anto007** [klincke/MicroWineBar#1]
Unable to run MicroWineBar due to the annoying below error. Yes, 'import tkinter' and 'import _tkinter' also fails on my Python-3.6.2. Any help would be highly appreciated. I tried searching online forums to fix this problem of not finding the module tkinter but despite me attempting the suggested fixes, the problem persists :-( 

Traceback (most recent call last):
  File "/home/user/tools/Python-3.6.2/virtualenv3/bin/microwinebar", line 6, in <module>
    from microwinebar.microwinebar import main
  File "/home/user/tools/Python-3.6.2/virtualenv3/lib/python3.6/site-packages/microwinebar/__init__.py", line 1, in <module>
    from .allsamples import AllSamples
  File "/home/user/tools/Python-3.6.2/virtualenv3/lib/python3.6/site-packages/microwinebar/allsamples.py", line 2, in <module>
    from tkinter import *
  File "/home/user/tools/Python-3.6.2/mybuild/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

**Comment by klincke** [comment]
I'm really sorry but I somehow missed your issue. 
I cannot replicate your error based on a python3.6.2 installation as tkinter is installed by default. 
If you are still interested in solving that issue I would like to help you but I need more information on the installed package versions.
